
spring:
  #数据源配置
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/car_home?serverTimezone=GMT%2B8&useSSL=false&useUnicode=true&charsetEncoding=utf-8
    username: root
    password: 123456.a
  #邮件配置
  mail:
    username: superb12580@163.com
    password: LAJEPVQBGNRQKGAW
    host: smtp.163.com
#  thymeleaf:
#    prefix: classpath:/templates/
#    suffix: .html
#    check-template-location: true  #check-tempate-location: 检查模板路径是否存在
#    cache: false  #cache: 是否缓存，开发模式下设置为false，避免改了模板还要重启服务器，线上设置为true，可以提高性能。
#  servlet:
#    multipart:
#      # 设置单个文件最大内存
#      max-file-size: 10MB
#      # 自定义文件上传路径
#      location: G:/upload_file/



#MyBatisPlus配置
mybatis-plus:
  configuration:
    #MyBatisPlus日志
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  global-config:
    db-config:
      #逻辑删除配置
      logic-delete-field: deleted
      logic-delete-value: 1
      logic-not-delete-value: 0
server:
  port: 8081
  servlet:
    context-path: '/car'

#oss对象存储
aliyun:
  oss:
    file:
      endpoint: oss-cn-beijing.aliyuncs.com
      keyid: LTAI5t8CZwDps19Z8Mgi1GiS
      keysecret: eg0ZBp9sdyCtRJJQiwO4KgGaiMYBWI
      bucketname: superb-car











